FROM docker.pkg.github.com/plstic/cmsc389b-spring21/base:latest
# need git?
RUN apt-get -y install sqlite3
# RUN wget https://cdn.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip && unzip chinook.zip
WORKDIR /src
